"""empty message

Revision ID: 3f820df33e3e
Revises: 
Create Date: 2020-03-30 21:10:41.332817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f820df33e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('slug', 'categories', ['slug'], unique=True)
    op.create_index('name', 'categories', ['name'], unique=True)
    op.create_table('posts_categories',
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='posts_categories_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='posts_categories_ibfk_2', ondelete='CASCADE'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('summary', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'posts', ['title'], unique=True)
    op.create_index('slug', 'posts', ['slug'], unique=True)
    op.create_table('file',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('upload_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('filename', 'file', ['filename'], unique=True)
    op.drop_table('Posts_Categories')
    op.drop_table('files')
    op.drop_table('Posts')
    op.drop_table('Categories')
    # ### end Alembic commands ###
